### ISSUE TITLE
下载脚本建议加入wget断点续传参数

### ISSUE THREAD

**Issue by WhisperChi** [wangzhaode/ChatGLM-MNN#10]
考虑到文件比较大、而且网络波动原因-_-||，建议加入wget断点续传参数

<img width="677" alt="002" src="https://user-images.githubusercontent.com/12483756/228427043-807db947-04dc-4578-adc3-1f36f2f70ede.png">

```bash
wget -c https://xxxxx
```

<img width="262" alt="003" src="https://user-images.githubusercontent.com/12483756/228427048-0107b6f2-2c8d-4020-b815-3c03c2ee0044.png">

**Comment by wangzhaode** [comment]
👌🏻好的

**Comment by wangzhaode** [comment]
https://github.com/wangzhaode/ChatGLM-MNN/commit/232328cbea80b81ba1f8d1a1d3287bd0c4c7c604
