### ISSUE TITLE
int4和int8量化模型用的是mnn的量化工具还是直接使用了ChatGLM官方的量化后的模型？

### ISSUE THREAD

**Issue by fcability** [wangzhaode/ChatGLM-MNN#101]
请问release中提供的int4和int8的mnn模型是怎么导出的？
1. onnx模型分段后转为mnn模型，使用mnn量化工具量化为int4和int8
2. 直接加载ChatGLM官方的int4和int8权重导出onnx模型，分段后转为mnn模型
3. 其他，请帮忙答疑

感谢！

**Comment by wangzhaode** [comment]
使用的是方法1

ChatGLM模型导出的是分段的浮点onnx模型；
在MNNConvert转换模型时做权值量化得到int4/int8量化的MNN模型；

**Comment by fcability** [comment]
感谢答复
