### ISSUE TITLE
mac上面编译mnn库生成的是.dylib而不是.so，后续想要android编译的时候，运行make -j8命令后报错：

### ISSUE THREAD

**Issue by gaolongxi** [wangzhaode/ChatGLM-MNN#103]
mac上面编译mnn库生成的是.dylib而不是.so，后续想要android编译的时候，运行make -j8命令后报错：

<img width="1035" alt="image" src="https://github.com/wangzhaode/ChatGLM-MNN/assets/57764575/4923713a-4904-4e01-8293-fa084ff0f878">

_Originally posted by @gaolongxi in https://github.com/wangzhaode/ChatGLM-MNN/issues/78#issuecomment-1662048617_

**Comment by wangzhaode** [comment]
编译安卓请按照README里面Android的编译方法, 这样在Mac上编译出来的也是so：
```
mkdir build
cd build
../android_build.sh
make -j8
```
