### ISSUE TITLE
关于Model权值命名区分的建议；eop、Segmentation fault问题解决。

### ISSUE THREAD

**Issue by WhisperChi** [wangzhaode/ChatGLM-MNN#15]
摘要：建议model按照权值不同来区分不同的文件名。

## 当前问题
int4、int8、float模型文件名称相同

|int4|int8|
|--|--|
|<img width="200" alt="200" src="https://user-images.githubusercontent.com/12483756/228626223-ef2824c8-9685-47f7-9b0c-2c147287b856.png">|<img width="200" alt="200" src="https://user-images.githubusercontent.com/12483756/228627185-b88240ef-3d80-4f67-9a98-d16230b1e8af.png">|

## 可能会导致的问题

1. 权重文件弄混，不直观
2. 代码混权重加载，运行失败

PS：实际上，我就是上述遇到了第二个问题。

程序出现过如下错误：
1. Q：你好     A：<eop>
2. Q：hello    A：hellohellohellohello（死循环）
4. Q：你好     A：Segmentation fault.

| | |
|--|--|
|<img width="200" alt="200" src="https://user-images.githubusercontent.com/12483756/228629104-d231d53d-cf3a-4f10-9d61-ba915cb8c169.png">|<img width="200" alt="200" src="https://user-images.githubusercontent.com/12483756/228629122-25f7a0b6-d9b7-403c-836e-e7b01d87e1e3.png">|

-_-|| 最近才开始接触深度学习这块，还是半知半懂，通过lldb、gdb才定位到问题。

有个小小建议，不知道模型可不可以加入权值相关的命名。或者models下面按照权值新建不同的目录，下载脚本做对应修改。

## 最后
已在Ubuntu22.04、MacOS M2芯片上成功运行。
附上运行成功的截图，感谢作者大大开源！！
<img width="293" alt="image" src="https://user-images.githubusercontent.com/12483756/228630724-a6d2f260-04ee-4c3e-96bb-93a14a6d9b8f.png">
Hello那边看起来还没回答完，慢慢等...

**Comment by wangzhaode** [comment]
嗯 写的略仓促，权重文件没有一开始是有后缀的，为了统一加载逻辑改成完全一样的了；

你的建议都非常nice，欢迎改一下提pr成为共同开发者！
