### ISSUE TITLE
貌似不支持上下文？

### ISSUE THREAD

**Issue by xx12138123** [wangzhaode/ChatGLM-MNN#23]
测试了挺多次，好像对没有在上文的基础上进行推理

**Comment by wangzhaode** [comment]
对  history没有传过去 之后加上

**Comment by wangzhaode** [comment]
已支持：https://github.com/wangzhaode/ChatGLM-MNN/commit/7a8027422281dcb38a64e6c2e0b3cf93ac403ffc
