### ISSUE TITLE
是否非常依赖pcie 带宽呢？

### ISSUE THREAD

**Issue by yichengming** [wangzhaode/ChatGLM-MNN#29]
我用的是p104-100 8g 矿渣跑 pci 只有1g的速度 是正常pci 3.0 x16的 1/16，速度很慢 一秒两个字那样子。我的处理器是e5 14核 28线程，内存32g ddr4，显卡利用率96%左右但是功耗不高，只有90w，处理只有四个核心占用。有办法优化下吗？我试了下回答结果还是不错的，脑筋急转弯比 文心强。

**Comment by wangzhaode** [comment]
PCIE带宽应该不是瓶颈，瓶颈是显存不够导致无法把全部层放到显卡推理，所以CPU推理时显卡占用会非常低；
