### ISSUE TITLE
出现段错误

### ISSUE THREAD

**Issue by wildkid1024** [wangzhaode/ChatGLM-MNN#32]
补充一下：

使用的是cuda没有fp16支持，但是使用的是fp16的MNN模型文件，然而即便在MNN-cpu only编译环境下也出现了该错误。
----
加载模型到layer 10的时候出现段错误，换了几台不同的x86_64机器均复现该问题。

运行log如下：

The device support dot:0, support fp16:0, support i8mm: 0
load ../resource/tokenizer/slim_vocab.txt ... Done!
load ../resource/models/glm_block_0.mnn model ... Done!
load ../resource/models/glm_block_1.mnn model ... Done!
load ../resource/models/glm_block_2.mnn model ... Done!
load ../resource/models/glm_block_3.mnn model ... Done!
load ../resource/models/glm_block_4.mnn model ... Done!
load ../resource/models/glm_block_5.mnn model ... Done!
load ../resource/models/glm_block_6.mnn model ... Done!
load ../resource/models/glm_block_7.mnn model ... Done!
load ../resource/models/glm_block_8.mnn model ... Done!
load ../resource/models/glm_block_9.mnn model ... Done!
load ../resource/models/glm_block_10.mnn model ... Done!
load ../resource/models/glm_block_11.mnn model ... Done!
load ../resource/models/glm_block_12.mnn model ... Done!
load ../resource/models/glm_block_13.mnn model ... Done!
load ../resource/models/glm_block_14.mnn model ... Done!
load ../resource/models/glm_block_15.mnn model ... Done!
load ../resource/models/glm_block_16.mnn model ... Done!
load ../resource/models/glm_block_17.mnn model ... Done!
load ../resource/models/glm_block_18.mnn model ... Done!
load ../resource/models/glm_block_19.mnn model ... Done!
load ../resource/models/glm_block_20.mnn model ... Done!
load ../resource/models/glm_block_21.mnn model ... Done!
load ../resource/models/glm_block_22.mnn model ... Done!
load ../resource/models/glm_block_23.mnn model ... Done!
load ../resource/models/glm_block_24.mnn model ... Done!
load ../resource/models/glm_block_25.mnn model ... Done!
load ../resource/models/glm_block_26.mnn model ... Done!
load ../resource/models/glm_block_27.mnn model ... Done!
load ../resource/models/lm.mnn model ... Done!

Q: hello

A: tokenizer:
tokenizer end
embedding end
layer 0
layer 1
layer 2
layer 3
layer 4
layer 5
layer 6
layer 7
layer 8
layer 9
段错误

在源码中添加的调试信息如下：
```cpp
int ChatGLM::forward(const std::vector<int>& input_ids) {
    AUTOTIME;
    mSeqLen += input_ids.size();
    auto hidden_states = gen_embedding(input_ids);
    auto attention_mask = gen_attention_mask(input_ids);
    auto position_ids = gen_position_ids(input_ids);
    std::cout<<"embedding end"<<std::endl;
#ifdef MINI_MEM_MODE
    char buffer[50];
    for (int i = 0; i < LAYER_SIZE; i++) {
        int loadIdx = i < LAYER_SIZE - 1 ? i + 1 : 0;
        std::string model_path = mModelDir + "/glm_block_" + std::to_string(loadIdx) + ".mnn";
        std::thread load_next_model(&ChatGLM::loadModel, this, model_path.c_str(), true, loadIdx);
        {
            // AUTOTIME;
            auto outputs = mModules[i]->onForward({hidden_states, attention_mask, position_ids, mHistoryVars[i]});
            hidden_states = outputs[0];
            mHistoryVars[i] = outputs[1];
        }
        mModules[i].reset();
        load_next_model.join();
    }
#else
    for (int i = 0; i < LAYER_SIZE; i++) {
        // AUTOTIME;
        auto outputs = mModules[i]->onForward({hidden_states, attention_mask, position_ids, mHistoryVars[i]});
        hidden_states = outputs[0];
        mHistoryVars[i] = outputs[1];
        std::cout<<"layer "<<i<<std::endl;
        // std::cout<<"hidden: "<<hidden_states[0]<<std::endl;
        // std::cout<<"mHistoryVars: "<<outputs[1]<<std::endl;
    }
#endif
    std::cout<<"onForward end"<<std::endl;
    return var_to_token(hidden_states);
}
```

**Comment by wangzhaode** [comment]
编译DEBUG版本用gdb看一下crash时的堆栈

**Comment by lindeer** [comment]
@wangzhaode 这个问题有进展吗，也遇到Segmentation fault (core dumped):

16G 内存、x86_64的机器、4核 i5-7500、编译的CPU版，下载的是int8模型

```
A: 
Thread 1 "cli_demo" received signal SIGSEGV, Segmentation fault.
0x00007ffff7481477 in fseek () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.35-22.fc36.x86_64 libgcc-12.2.1-4.fc36.x86_64 libstdc++-12.2.1-4.fc36.x86_64
(gdb) bt
#0  0x00007ffff7481477 in fseek () from /lib64/libc.so.6
#1  0x00007ffff7f79c10 in ChatGLM::gen_embedding (this=0x7fffffffd3f0, input_ids=std::vector of length 7, capacity 8 = {...})
    at /home/wesley/WorkPlace/chatGPT/chatGLM-MNN/src/chat.cpp:174
#2  0x00007ffff7f7a249 in ChatGLM::forward (this=0x7fffffffd3f0, input_ids=std::vector of length 7, capacity 8 = {...})
    at /home/wesley/WorkPlace/chatGPT/chatGLM-MNN/src/chat.cpp:236
#3  0x00007ffff7f78a17 in ChatGLM::response (this=0x7fffffffd3f0, input_str="人生的意义是什么", os=0x4e4500 <std::cout@GLIBCXX_3.4>)
    at /home/wesley/WorkPlace/chatGPT/chatGLM-MNN/src/chat.cpp:49
#4  0x00007ffff7f78628 in ChatGLM::chat (this=0x7fffffffd3f0) at /home/wesley/WorkPlace/chatGPT/chatGLM-MNN/src/chat.cpp:26
#5  0x0000000000479da4 in main (argc=1, argv=0x7fffffffdb28) at /home/wesley/WorkPlace/chatGPT/chatGLM-MNN/demo/cli_demo.cpp:25
```
有可能是模型下载出差错了吗？

**Comment by wildkid1024** [comment]
可能地址越界，纯CPU要消耗30g左右内存。

**Comment by lindeer** [comment]
@wildkid1024 谢谢，int4模型会不会好点？会点多少内存

**Comment by wildkid1024** [comment]
mnn对量化的支持还不够完善，实际上int4模型并不是以int4加载进内存的。

**Comment by WangFengtu1996** [comment]
* 关于项目提到的编译使用低内存的方案，那就是加载的时候还是需要大内存？ 只是运行起来之后内存能降低到2G？

**Comment by lindeer** [comment]
@WangFengtu1996 它的2G内存不知道怎么得出来的，实际加载不起来，我怀疑少了一个0

**Comment by wildkid1024** [comment]
低内存模式下2g是可以跑的，逻辑就是每个block在2g左右，时间换空间，就是结果会特别慢。

**Comment by wangzhaode** [comment]
> mnn对量化的支持还不够完善，实际上int4模型并不是以int4加载进内存的。

最近更新后int4只需要3G内存了， Android demo app可以测试

**Comment by HJT9328** [comment]
> 编译DEBUG版本用gdb看一下crash时的堆栈

想问一下大神如何编译DEBUG版本呢

**Comment by wildkid1024** [comment]
建议详细阅读mnn的cmake选项。
