### ISSUE TITLE
请问是否可以添加METAL的支持？便于在mac上加速

### ISSUE THREAD

**Issue by Min9X1n** [wangzhaode/ChatGLM-MNN#35]
查阅资料MNN支持METAL，因此已经尝试：
1、在MNN编译中加入-DMNN_METAL=ON -DMNN_ARM82=ON
2、修改了chat.cpp的 config.type= MNN_FORWARD_METAL;

编译后能够允许，但是开始聊天后，在编译后出现“Don't support type [While]”、“The Creator Don't support type [BinaryOp]”等多个报错。等待后，最后持续输出“Don't support type [While], onnx::Concat_680”、“Don't support type [While], onnx::Concat_683”并在网页中输出“<unk><unk><unk><unk>...<unk>”

自己能力有限，请问作者有没有相关的计划，或者我该如何修改呢

**Comment by wangzhaode** [comment]
MNN是支持Metal的，从您的报错信息来看应该是目前算子支持不太好导致的；这个的话需要Metal后端实现算子才可以

**Comment by Min9X1n** [comment]
哦哦好的，感谢开发者的付出！
