### ISSUE TITLE
to onnx problems

### ISSUE THREAD

**Issue by frankzhao112** [wangzhaode/ChatGLM-MNN#40]
![image](https://user-images.githubusercontent.com/128885107/232412227-b01864c7-e722-4121-a195-29f6bd21eda2.png)
请问一下，我这里显示killed， 是失败了，还是成功了？
还有就是转onnx 是不是不用使用gpu？

**Comment by YueGeek** [comment]
您好，我的错误和您一样，我将code=src/2449bdc9d85103734ae987bdc94eafa7fec2145d/modeling_chatglm.py改成了code=modeling_chatglm.py，但是还是报相同的错误，请问您还更改了那些内容吗？
![image](https://github.com/wangzhaode/ChatGLM-MNN/assets/96854562/26e1850d-31b5-4178-b5f8-13acc7bccd86)
