### ISSUE TITLE
Mac上编译web_demo.cpp报错

### ISSUE THREAD

**Issue by justin8736** [wangzhaode/ChatGLM-MNN#46]
g++ -std=c++11 -I../include web_demo.cpp -o web_demo
Undefined symbols for architecture x86_64:
  "ChatGLM::init(float)", referenced from:
      ChatGLM::ChatGLM(float, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in web_demo-baa4c0.o
  "ChatGLM::response(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >*)", referenced from:
      main::$_1::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const in web_demo-baa4c0.o
ld: symbol(s) not found for architecture x86_64

请问这个是什么原因？

**Comment by wangzhaode** [comment]
你这个源文件 没有加`chat.cpp` 按照readme的方式用CMake编译
