### ISSUE TITLE
An issue of C++ standard when compiling on Windows

### ISSUE THREAD

**Issue by noteas** [wangzhaode/ChatGLM-MNN#53]
Dear ChatGLM-MNN contributors,
Hi! Recently, when I was compiling ChatGLM-MNN on Windows 10 using MSVC 2022, I encountered such a weird problem as following:
`
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\include\filesystem(13): warning STL4038: The contents of <filesystem> are available only with C++17 or later.
...
ChatGLM-MNN\include\chat.hpp(70): error C2039: "filesystem": Not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\include\algorithm(76): note: See the declaration of 'std'
...
`
However, it has not escaped my notice that there's a warning `cl : Command line warning D9002 : ignoring unknown option '-std=c++17'` at the top. It seems that you used a gcc-style option for MSVC.
The origin of this can date back to #51, CMakeLists.txt, Line 4 where the bug lain: `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17")` This fails to take portability into account.
Just by the way, no offense intended, I consider the person who wrote this piece of code do not know the correct way of setting C++ standard for CMake.
In a word, the line above should be substituted with `set(CMAKE_CXX_STANDARD 17)`.
I hope my suggestions are helpful to you.

Regards,
noteas

**Comment by wangzhaode** [comment]
Thanks! Fixed this bug in https://github.com/wangzhaode/ChatGLM-MNN/commit/d0d3684caf25e434236911d795e1ef5dda10f86c .

**Comment by wangzhaode** [comment]
Thanks! Remove the `filesystem` in this pr https://github.com/wangzhaode/ChatGLM-MNN/pull/56
