### ISSUE TITLE
安卓端编译，无法使用filesystem

### ISSUE THREAD

**Issue by xiaoguoer** [wangzhaode/ChatGLM-MNN#55]
make错误如下：
`[ 25%] Building CXX object CMakeFiles/chat.dir/src/chat.cpp.o
[ 50%] Linking CXX shared library libchat.so
[ 50%] Built target chat
[ 75%] Building CXX object CMakeFiles/cli_demo.dir/demo/cli_demo.cpp.o
[100%] Linking CXX executable cli_demo
CMakeFiles/cli_demo.dir/demo/cli_demo.cpp.o: In function `std::__ndk1::__fs::filesystem::current_path()':
/home/xiaoguo/Android/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/filesystem:1458: undefined reference to `std::__ndk1::__fs::filesystem::__current_path(std::__ndk1::error_code*)'
CMakeFiles/cli_demo.dir/demo/cli_demo.cpp.o: In function `std::__ndk1::__fs::filesystem::status(std::__ndk1::__fs::filesystem::path const&, std::__ndk1::error_code&)':
/home/xiaoguo/Android/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/filesystem:1914: undefined reference to `std::__ndk1::__fs::filesystem::__status(std::__ndk1::__fs::filesystem::path const&, std::__ndk1::error_code*)'
CMakeFiles/cli_demo.dir/demo/cli_demo.cpp.o: In function `std::__ndk1::__fs::filesystem::path::has_root_directory() const':
/home/xiaoguo/Android/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/filesystem:1084: undefined reference to `std::__ndk1::__fs::filesystem::path::__root_directory() const'
CMakeFiles/cli_demo.dir/demo/cli_demo.cpp.o: In function `std::__ndk1::__fs::filesystem::path::has_filename() const':
/home/xiaoguo/Android/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/filesystem:1096: undefined reference to `std::__ndk1::__fs::filesystem::path::__filename() const'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/cli_demo.dir/build.make:100：cli_demo] 错误 1
make[1]: *** [CMakeFiles/Makefile2:111：CMakeFiles/cli_demo.dir/all] 错误 2
make: *** [Makefile:91：all] 错误 2`

**Comment by wangzhaode** [comment]
更新到最新的代码在测试一下看看能否编译

**Comment by xiaoguoer** [comment]
> 更新到最新的代码在测试一下看看能否编译

链接不上-lstdc++fs。
`[ 50%] Linking CXX shared library libchat.so
/home/xiaoguo/Android/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lstdc++fs
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/chat.dir/build.make:99：libchat.so] 错误 1
make[1]: *** [CMakeFiles/Makefile2:85：CMakeFiles/chat.dir/all] 错误 2
make: *** [Makefile:91：all] 错误 2`

**Comment by xiaoguoer** [comment]
> 更新到最新的代码在测试一下看看能否编译

直接不用filesystem会不会对模型的推理性能有影响？（去掉filesystem编译通过了）

**Comment by wangzhaode** [comment]
fixed: https://github.com/wangzhaode/ChatGLM-MNN/pull/56
