### ISSUE TITLE
咨询：关于lm.mnn导出的问题

### ISSUE THREAD

**Issue by Truoji** [wangzhaode/ChatGLM-MNN#60]
1、在提供的onnx模型中，我看到lm_head.onnx和一个lm_head对应的权重，我想应该可以通过onnx计算图和权重能够导出到mnn模型，但是我通过这两导出的mnn是不能使用的，并且导出的MatMul是乱的。错误提示信息是resize error for lm_logits 130328 ->533823488
2、我下载提供的lm.mnn模型发现来源是caffe，并且多了一个argmax层；我想请教一下这个模型是通过onnx和权重得到的吗？我使用mnn的测试工具GetmnnInfo查看到input shape是[4096, 1]。所以这部分需要自己更改源模型代码导出吗？

**Comment by wangzhaode** [comment]
哦 我提供的lm.mnn确实是经过修改之后的；这个模型的导出方法我明天补充一下

**Comment by wangzhaode** [comment]
https://github.com/wangzhaode/ChatGLM-MNN/blob/master/export_script/gen_lm_onnx.py

**Comment by guohuanliang1** [comment]
slim_word_embeddings.bin的导出方法是什么？
