### ISSUE TITLE
速度感觉不行，没有python版本快

### ISSUE THREAD

**Issue by lhray** [wangzhaode/ChatGLM-MNN#67]
相同的GPU，P100上跑，python 版本一个token大概70ms左右，
C++ 版本就很慢：
Layer:0 onForward 4507 
Layer:1 onForward 15484 
Layer:2 onForward 15554 
Layer:3 onForward 15719 
Layer:4 onForward 16667 
Layer:5 onForward 16161 
Layer:6 onForward 16020 
Layer:7 onForward 15885 
Layer:8 onForward 15834 
Layer:9 onForward 15770 
Layer:10 onForward 15735 
Layer:11 onForward 16289 
Layer:12 onForward 16055 
Layer:13 onForward 15555 
Layer:14 onForward 15535 
Layer:15 onForward 16117 
Layer:16 onForward 15519 
Layer:17 onForward 15601 
Layer:18 onForward 15613 
Layer:19 onForward 16207 
Layer:20 onForward 15605 
Layer:21 onForward 16140 
Layer:22 onForward 16320 
Layer:23 onForward 16028 
Layer:24 onForward 15961 
Layer:25 onForward 15884 
Layer:26 onForward 15811 
Layer:27 onForward 15827 
var_to_token reshape: 19
====var_to_token 277788
======================================forward: 711917 [果子]

**Comment by wangzhaode** [comment]
嗯 CUDA在优化中  之前在部分显卡上性能略差
