### ISSUE TITLE
大佬们，帮我看下为什么我这启动cli_demo的时候加载的是fp16模型，我下载的是int8模型

### ISSUE THREAD

**Issue by yuanshuangxiong** [wangzhaode/ChatGLM-MNN#70]
load ../resource/models/fp16/glm_block_27.mnn model ... Error for open ../resource/models/fp16/glm_block_27.mnn

**Comment by yuanshuangxiong** [comment]
多谢大佬

**Comment by yuyi2439** [comment]
> 多谢大佬

解决完问题请关闭issue

**Comment by CrystalRays** [comment]
为啥我加 -d 显示没有这个参数

**Comment by yuyi2439** [comment]
> 为啥我加 -d 显示没有这个参数

请发一下整个启动命令

**Comment by xu-mengnan** [comment]
> > 为啥我加 -d 显示没有这个参数
> 
> 请发一下整个启动命令

<img width="509" alt="图片" src="https://github.com/wangzhaode/ChatGLM-MNN/assets/36294047/65ff2c09-b40a-4c75-ae55-36e874809c63">

**Comment by xu-mengnan** [comment]
> > > > 为啥我加 -d 显示没有这个参数
> > > 
> > > 
> > > 请发一下整个启动命令
> > 
> > 
> > <img alt="图片" width="509" src="https://user-images.githubusercontent.com/36294047/246761761-65ff2c09-b40a-4c75-ae55-36e874809c63.png">
> 
> 新版才有，可能你要更新一下？或者直接用--model_dir指定目录也是可以的。

使用的就是最新版本的呀

**Comment by xu-mengnan** [comment]
> > > > > > 为啥我加 -d 显示没有这个参数
> > > > > 
> > > > > 
> > > > > 请发一下整个启动命令
> > > > 
> > > > 
> > > > <img alt="图片" width="509" src="https://user-images.githubusercontent.com/36294047/246761761-65ff2c09-b40a-4c75-ae55-36e874809c63.png">
> > > 
> > > 
> > > 新版才有，可能你要更新一下？或者直接用--model_dir指定目录也是可以的。
> > 
> > 
> > 使用的就是最新版本的呀
> 
> 哦，新版好像砍掉了这个功能，那还是用--mode_dir吧

请问，我应该填入什么呢，另外，我新填入了一个issues，也辛苦大佬帮忙看一下

**Comment by wangzhaode** [comment]
最新版把-d删掉了 直接-m 指向你的模型路径即可

**Comment by yuanshuangxiong** [comment]
1
