### ISSUE TITLE
运行cli_demo -d int4时出现空文件指针

### ISSUE THREAD

**Issue by yuyi2439** [wangzhaode/ChatGLM-MNN#72]
环境：Android
MNN：2.5.1
最后一次commit：ba8ad5a

~/ChatGLM-MNN/build $ ./cli_demo -d int4        model path is ../resource/models/int4
parsed /proc/cpuinfo Hardware = "Qualcomm Technologies, Inc SM8250"
The device support i8sdot:1, support fp16:1, support i8mm: 0
Can't Find type=2 backend, use 3 instead
load ../resource/tokenizer/slim_vocab.txt ... Done!
                                                
Q: 你好                                         
A: FORTIFY: fseeko: null FILE*                  Aborted

**Comment by yuyi2439** [comment]
发现问题了，是BUILD_MINI_MEM_MODE导致的，目前不知道咋解决

**Comment by wangzhaode** [comment]
需要lm.bin文件

**Comment by yuyi2439** [comment]
> 需要lm.bin文件

我确定我下载了lm.bin

**Comment by yuyi2439** [comment]
> 需要lm.bin文件

我确定我下载了lm.bin
/
/

**Comment by yuyi2439** [comment]
我在WSL2上尝试，依旧有问题
$ ./cli_demo -d int4
Device name: NVIDIA GeForce MX450
Compute capability: 7.5
GPU Device supports FP16 computation
Total global memory: 1.99976G
Total available memory: 1.54723G
model path is ../resource/models/int4
The device support i8sdot:0, support fp16:0, support i8mm: 0
load ../resource/tokenizer/slim_vocab.txt ... Done!

Q: 你好

A: Segmentation fault

如果不启用BUILD_MINI_MEM_MODE是可以正常运行的

**Comment by yuyi2439** [comment]
[    std::string file_path = mModelDir + "/slim_lm.bin";](https://github.com/wangzhaode/ChatGLM-MNN/blob/ba8ad5aded0e527a9cb26460c10f5a5b6cc40ff9/src/chat.cpp#LL284C56-L284C56)
哦哦，你指的是slim_lm.bin吧
我在releases里找到了，谢谢

我还有个问题：为啥slim_lm.bin比lm.bin要大

**Comment by yuyi2439** [comment]
看错了，后缀都不一样，关闭了
