### ISSUE TITLE
int8模式下生成连续的<sop><sop>

### ISSUE THREAD

**Issue by xunbing** [wangzhaode/ChatGLM-MNN#76]
int8模式下生成连续的<sop><sop>，如图
![image](https://github.com/wangzhaode/ChatGLM-MNN/assets/16739817/6631726f-5654-4c0f-9ad2-bc72578db90a)
请问可能是什么原因呢

CPU模式是没问题的
![image](https://github.com/wangzhaode/ChatGLM-MNN/assets/16739817/343de9c0-c26e-4336-b513-6071315ff59d)

=========更新========
发现T4卡上生成<sop><sop>，但是P40卡可以正常輸出。

**Comment by wangzhaode** [comment]
更新一下MNN的代码重新编译一下试试看
