### ISSUE TITLE
windows cpu最后一步没有可执行文件 报错

### ISSUE THREAD

**Issue by HaviZou** [wangzhaode/ChatGLM-MNN#79]
PS D:\ChatGLM-MNN\build> cmake --build . -- /m:8
MSBuild version 17.5.1+f6fdcf537 for .NET Framework

cl : 命令行  warning D9002: 忽略未知??“-std=c++11” [D:\ChatGLM-MNN\build\chat.vcxproj]
  chat.cpp
D:\ChatGLM-MNN\src\chat.cpp(1,1): warning C4819: ?文件包含不能在当前代??(932)中表示的字符。?将?文件保存? Unicode 格式以 防止数据?失 [D:\ChatGLM-MNN\bu
ild\chat.vcxproj]
D:\ChatGLM-MNN\include\cppjieba\Trie.hpp(1,1): warning C4819: ?文件包含不能在当前代??(932)中表示的字符。?将?文件保存? Unicode 格式以防止数据?失 [D:\C
hatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\include\cppjieba\HMMSegment.hpp(162,1): warning C4267: “=”: 从“size_t”??到“_Ty”，可能?失数据 [D:\ChatGLM-MNN\bui
ld\chat.vcxproj]
          with
          [
              _Ty=int
          ]
D:\ChatGLM-MNN\include\cppjieba\HMMSegment.hpp(178,1): warning C4267: “初始化”: 从“size_t”??到“int”，可能?失数据 [D:\ChatGLM-MNN\b
uild\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(50,64): error C2001: 常量中有?行符 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(51,5): error C2062: 意外的?型“auto” [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(54,39): error C2065: “prompt”: 未声明的??符 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(55,34): error C3536: “input_ids”: 初始化之前无法使用 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(55,17): error C2664: “int ChatGLM::forward(const std::vector<int,std::allocator<int>> &)”:
无法将参数 1 从“int”???“const std::vector<int,std::allocator<int>> &” [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(55,25): message : 原因如下: 无法从“int”???“const std::vector<int,std::allocator<int>>” [D:\ChatGLM
-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(55,25): message : class“std::vector<int,std::allocator<int>>”的?造函数声明?“explicit” [D:\ChatGLM
-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\include\chat.hpp(60,9): message : 参?“ChatGLM::forward”的声明 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(55,17): message : ??匹配参数列表“(int)”? [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(69,53): error C2017: 非法的??序列 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(69,55): error C2001: 常量中有?行符 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(69,54): error C2146: ?法??: 缺少“)”(在??符“n”的前面) [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(104,36): warning C4267: “初始化”: 从“size_t”??到“int”，可能?失数据 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(109,21): error C2001: 常量中有?行符 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(110,5): error C2143: ?法??: 缺少“)”(在“if”的前面) [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(110,5): warning C4267: “=”: 从“size_t”??到“int”，可能?失数据 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(110,5): error C2143: ?法??: 缺少“;”(在“if”的前面) [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(158,24): warning C4244: “初始化”: 从“double”??到“int”，可能?失数据 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(163,25): warning C4305: “=”: 从“double”到“float”截断 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(169,30): warning C4305: “+=”: 从“double”到“float”截断 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(193,18): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fo
pen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\ChatGLM-MNN\build\
chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(209,35): warning C4267: “初始化”: 从“size_t”??到“int”，可能?失数据 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(243,35): warning C4267: “初始化”: 从“size_t”??到“int”，可能?失数据 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(262,30): warning C4267: “+=”: 从“size_t”??到“int”，可能?失数据 [D:\ChatGLM-MNN\build\chat.vcxproj]

**Comment by HaviZou** [comment]
是不是调整兼容其它平台时，影响到windows的代码了？

**Comment by wangzhaode** [comment]
> 

错误是这种编译问题导致：

D:\ChatGLM-MNN\src\chat.cpp(50,64): error C2001: 常量中有?行符 [D:\ChatGLM-MNN\build\chat.vcxproj]

我看了下C++代码没有问题 你更新到最新试试看？

**Comment by HaviZou** [comment]
> 



> > 
> 
> 错误是这种编译问题导致：
> 
> D:\ChatGLM-MNN\src\chat.cpp(50,64): error C2001: 常量中有?行符 [D:\ChatGLM-MNN\build\chat.vcxproj]
> 
> 我看了下C++代码没有问题 你更新到最新试试看？

所有代码都是今天下载的，代码里有没有中文字符命令符之类的？我这个系统有点特殊，默认活动控制台代码页是日文的，但我已经尝试切换到中文和utf-8,还是不能编译成功。

**Comment by wangzhaode** [comment]
最新代码的话那应该是编码问题，50行中有中文字符，你修改一下文件的编码试试

**Comment by HaviZou** [comment]
> 最新代码的话那应该是编码问题，50行中有中文字符，你修改一下文件的编码试试

确实是编码问题，我将chat.cpp默认的UTF-8改为ANSI后，可以编译成功，但源码里的"问 答"字符估计不能用了，是否会影响交互时字符串截取？
--------------------------------------最新编译反馈  编译成功但有警告------------------------------------------------
PS D:\ChatGLM-MNN\build>  cmake --build . -- /m:8
MSBuild version 17.5.1+f6fdcf537 for .NET Framework

cl : 命令行  warning D9002: 忽略未知??“-std=c++11” [D:\ChatGLM-MNN\build\chat.vcxproj]
  chat.cpp
D:\ChatGLM-MNN\include\cppjieba\Trie.hpp(1,1): warning C4819: ?文件包含不能在当前代??(932)中表示的字符。?将?文件保存? Unicode 格式以防止数据?失 [D:\C
hatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\include\cppjieba\HMMSegment.hpp(162,1): warning C4267: “=”: 从“size_t”??到“_Ty”，可能?失数据 [D:\ChatGLM-MNN\bui
ld\chat.vcxproj]
          with
          [
              _Ty=int
          ]
D:\ChatGLM-MNN\include\cppjieba\HMMSegment.hpp(178,1): warning C4267: “初始化”: 从“size_t”??到“int”，可能?失数据 [D:\ChatGLM-MNN\b
uild\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(104,36): warning C4267: “初始化”: 从“size_t”??到“int”，可能?失数据 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(109,25): warning C4267: “=”: 从“size_t”??到“int”，可能?失数据 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(158,24): warning C4244: “初始化”: 从“double”??到“int”，可能?失数据 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(163,25): warning C4305: “=”: 从“double”到“float”截断 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(169,30): warning C4305: “+=”: 从“double”到“float”截断 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(159,10): warning C4101: “buffer”: 未引用的局部?量 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(193,18): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fo
pen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\ChatGLM-MNN\build\
chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(209,35): warning C4267: “初始化”: 从“size_t”??到“int”，可能?失数据 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(243,35): warning C4267: “初始化”: 从“size_t”??到“int”，可能?失数据 [D:\ChatGLM-MNN\build\chat.vcxproj]
D:\ChatGLM-MNN\src\chat.cpp(262,30): warning C4267: “+=”: 从“size_t”??到“int”，可能?失数据 [D:\ChatGLM-MNN\build\chat.vcxproj]
  chat.vcxproj -> D:\ChatGLM-MNN\build\Debug\chat.lib
  Building Custom Rule D:/ChatGLM-MNN/CMakeLists.txt
  Building Custom Rule D:/ChatGLM-MNN/CMakeLists.txt
cl : 命令行  warning D9002: 忽略未知??“-std=c++11” [D:\ChatGLM-MNN\build\cli_demo.vcxproj]
  cli_demo.cpp
cl : 命令行  warning D9002: 忽略未知??“-std=c++11” [D:\ChatGLM-MNN\build\web_demo.vcxproj]
  web_demo.cpp
  cli_demo.vcxproj -> D:\ChatGLM-MNN\build\Debug\cli_demo.exe
  web_demo.vcxproj -> D:\ChatGLM-MNN\build\Debug\web_demo.exe
  Building Custom Rule D:/ChatGLM-MNN/CMakeLists.txt

**Comment by wangzhaode** [comment]
只是提示词，你可以改成`Q A` 不影响你使用的
