### ISSUE TITLE
MNN构建，README有一处需要补充下~

### ISSUE THREAD

**Issue by WhisperChi** [wangzhaode/ChatGLM-MNN#8]
感谢分享，最近出于个人兴趣在看GLM相关东西

<img width="470" alt="001" src="https://user-images.githubusercontent.com/12483756/228403829-4b5f0b8f-d514-4411-be18-26abb8e83cf1.png">
如图箭头处，漏了一句 

``` bash
cd build
```

再次感谢作者大大~

**Comment by wangzhaode** [comment]
是的 感谢提醒 我加一下

**Comment by wangzhaode** [comment]
Done!
https://github.com/wangzhaode/ChatGLM-MNN/commit/928735f4ee3c08f31594d7de811089f53fc77a23
