### ISSUE TITLE
fp16 embedding问题

### ISSUE THREAD

**Issue by zhiyaotl** [wangzhaode/ChatGLM-MNN#95]
![image](https://github.com/wangzhaode/ChatGLM-MNN/assets/95298354/e699440f-1d3a-4d42-b7da-32a706da2d22)
请问，这里补个0是为了fp16转fp32吗？

**Comment by wangzhaode** [comment]
这里用的是bf16, bf16转fp32就是高16位补0就可以了

**Comment by zhiyaotl** [comment]
这里是不是还和平台大小端强相关，也可能在低16位补？
